[profile.default]
solc = '0.8.21'
src = "src"
out = "out"
libs = ["lib"]
remappings = ['solady/=lib/solady/src/', 'forge-std/=lib/forge-std/src/']
optimizer_runs = 9_999_999
via_ir = true

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
